"""empty message

Revision ID: 16e20e71fce5
Revises: 284f1d50a99e
Create Date: 2019-08-25 12:05:58.781631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16e20e71fce5'
down_revision = '284f1d50a99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencers_required')
    op.add_column('campaign', sa.Column('no_of_influencers1', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('no_of_influencers2', sa.Integer(), nullable=True))
    op.add_column('pricing_details', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('pricing_details', sa.Column('follower_range', sa.Integer(), nullable=True))
    op.add_column('pricing_details', sa.Column('payout', sa.Integer(), nullable=True))
    op.drop_column('pricing_details', 'est_duration')
    op.drop_column('pricing_details', 'payout_to_influencers')
    op.drop_column('pricing_details', 'follower_upper_range')
    op.drop_column('pricing_details', 'follower_lower_range')
    op.drop_column('pricing_details', 'price_to_brand')
    op.drop_column('pricing_details', 'est_engagement')
    op.drop_column('pricing_details', 'est_videoviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_details', sa.Column('est_videoviews', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('est_engagement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('price_to_brand', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('follower_lower_range', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('follower_upper_range', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('payout_to_influencers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pricing_details', sa.Column('est_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('pricing_details', 'payout')
    op.drop_column('pricing_details', 'follower_range')
    op.drop_column('pricing_details', 'cost')
    op.drop_column('campaign', 'no_of_influencers2')
    op.drop_column('campaign', 'no_of_influencers1')
    op.create_table('influencers_required',
    sa.Column('inf_req_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('range6', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], name='influencers_required_ibfk_1'),
    sa.PrimaryKeyConstraint('inf_req_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
