"""empty message

Revision ID: 2c57824c4adc
Revises: 814e31501d5e
Create Date: 2019-08-20 08:05:02.647171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c57824c4adc'
down_revision = '814e31501d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spoc_details', sa.Column('designation', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spoc_details', 'designation')
    # ### end Alembic commands ###
