"""empty message

Revision ID: 3202a3c5698f
Revises: 9b07f18251c6
Create Date: 2019-08-19 10:35:39.788332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3202a3c5698f'
down_revision = '9b07f18251c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_done', sa.Column('desc', sa.String(length=200), nullable=True))
    op.add_column('posts_done', sa.Column('rules', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts_done', 'rules')
    op.drop_column('posts_done', 'desc')
    # ### end Alembic commands ###
