"""empty message

Revision ID: 814e31501d5e
Revises: da3810dfab82
Create Date: 2019-08-20 07:58:43.535629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814e31501d5e'
down_revision = 'da3810dfab82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_details', sa.Column('contact_no', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_details', 'contact_no')
    # ### end Alembic commands ###
