"""empty message

Revision ID: 9b07f18251c6
Revises: d2729fc5dfd0
Create Date: 2019-08-18 17:56:12.296692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b07f18251c6'
down_revision = 'd2729fc5dfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('pay_type', sa.Integer(), nullable=True))
    op.drop_column('payments', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('payments', 'pay_type')
    # ### end Alembic commands ###
