"""empty message

Revision ID: ab303c2d086f
Revises: 3202a3c5698f
Create Date: 2019-08-20 07:23:50.538289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab303c2d086f'
down_revision = '3202a3c5698f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube', sa.Column('channel_link', sa.String(length=100), nullable=True))
    op.add_column('youtube', sa.Column('subscriber_count', sa.Integer(), nullable=True))
    op.drop_column('youtube', 'profile_url')
    op.drop_column('youtube', 'follower_count')
    op.drop_column('youtube', 'access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube', sa.Column('access_token', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('youtube', sa.Column('follower_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('youtube', sa.Column('profile_url', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('youtube', 'subscriber_count')
    op.drop_column('youtube', 'channel_link')
    # ### end Alembic commands ###
