"""empty message

Revision ID: b877588894e4
Revises: e07ec7839e48
Create Date: 2019-08-16 02:15:54.160175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b877588894e4'
down_revision = 'e07ec7839e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_details', sa.Column('mobile_no', sa.String(length=15), nullable=False))
    op.alter_column('influencer_details', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('influencer_details', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('influencer_details', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('influencer_details', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('influencer_details', 'mobile_no')
    # ### end Alembic commands ###
