"""empty message

Revision ID: ca8a88f29652
Revises: dc1cf3e0e9d9
Create Date: 2019-08-16 02:27:33.491963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca8a88f29652'
down_revision = 'dc1cf3e0e9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_details', sa.Column('updated', sa.Boolean(), nullable=True))
    op.drop_column('influencer_details', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_details', sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('influencer_details', 'updated')
    # ### end Alembic commands ###
