"""empty message

Revision ID: d2729fc5dfd0
Revises: 92cea535fbda
Create Date: 2019-08-18 12:25:43.999618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2729fc5dfd0'
down_revision = '92cea535fbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('desc', sa.String(length=4000), nullable=True))
    op.add_column('campaign', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'name')
    op.drop_column('campaign', 'desc')
    # ### end Alembic commands ###
