"""empty message

Revision ID: da3810dfab82
Revises: ab303c2d086f
Create Date: 2019-08-20 07:32:12.412505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da3810dfab82'
down_revision = 'ab303c2d086f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('influencer_details_ibfk_2', 'influencer_details', type_='foreignkey')
    op.drop_constraint('influencer_details_ibfk_1', 'influencer_details', type_='foreignkey')
    op.drop_constraint('influencer_details_ibfk_4', 'influencer_details', type_='foreignkey')
    op.drop_constraint('influencer_details_ibfk_3', 'influencer_details', type_='foreignkey')
    op.drop_column('influencer_details', 'yt_id')
    op.drop_column('influencer_details', 'fb_id')
    op.drop_column('influencer_details', 'insta_id')
    op.drop_column('influencer_details', 'tw_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_details', sa.Column('tw_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('influencer_details', sa.Column('insta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('influencer_details', sa.Column('fb_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('influencer_details', sa.Column('yt_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('influencer_details_ibfk_3', 'influencer_details', 'twitter', ['tw_id'], ['tw_id'])
    op.create_foreign_key('influencer_details_ibfk_4', 'influencer_details', 'youtube', ['yt_id'], ['yt_id'])
    op.create_foreign_key('influencer_details_ibfk_1', 'influencer_details', 'instagram', ['insta_id'], ['insta_id'])
    op.create_foreign_key('influencer_details_ibfk_2', 'influencer_details', 'facebook', ['fb_id'], ['fb_id'])
    # ### end Alembic commands ###
