"""empty message

Revision ID: e07ec7839e48
Revises: 
Create Date: 2019-08-16 02:10:16.652906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07ec7839e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'influencer_details', 'youtube', ['yt_id'], ['yt_id'])
    op.create_foreign_key(None, 'influencers_involved', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'influencers_involved', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'interest_details', 'influencer_details', ['influencer_id'], ['influencer_id'])
    op.create_foreign_key(None, 'interest_details', 'campaign', ['campaign'], ['campaign_id'])
    op.create_foreign_key(None, 'interest_details', 'brand_details', ['brand_id'], ['brand_id'])
    op.create_foreign_key(None, 'rel_campaign_influencer_inv', 'campaign', ['campaign_id'], ['campaign_id'])
    op.create_foreign_key(None, 'youtube', 'influencer_details', ['influencer_id'], ['influencer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube', type_='foreignkey')
    op.drop_constraint(None, 'rel_campaign_influencer_inv', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'interest_details', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_constraint(None, 'influencers_involved', type_='foreignkey')
    op.drop_constraint(None, 'influencer_details', type_='foreignkey')
    # ### end Alembic commands ###
